### ISSUE TITLE
How is your daily workflow with this approach

### ISSUE THREAD

**Issue by rccavalcante** [Wavesonics/GodotClientServer#2]
Hey there @Wavesonics ! Thanks for the explanation of how this approach works, and for making all the files available for us. As you said, most of the networking tutorials focus on p2p and the ones regarding dedicated server show how to set up everything using two separate projects, and that's what I did.

I'm currently playing around on making a dedicated server and a client, and since I do this entirely for fun and alone, I'm finding difficult to maintain two separate projects. Even though my project is really small, I already noticed I'm repeating the same code on both client and server. That being said, I think the approach of having everything inside one project but being able to export and run them separately is the best choice.

I'm just concerned about what would be the workflow for doing this. Currently, I keep two/three instances of the Godot engine open with both projects on each, and every time I change something, I just restart the game on each. It's a bit of a pain to have a lot of windows open, sometimes all three editors, one server, and 2 clients at once, but still it's very quick to test everything. I just need to click on the play button.

I wanted to know from you what would be the workflow of having the server and client inside the same project. If I want to test the server part, would I need to set up the features and export settings, then export it and execute the binary directly or with the headless version in the terminal and then change everything and do the same for the client part?

**Comment by Wavesonics** [comment]
That is one way you could do it. Also your method of having multiple versions of the editor open should still work.

I have a pretty decent sized project using this arcitecture now: https://github.com/FugitiveTheGame/Fugitive3D

And I started working on a some what better method for doing testing:
I wrote some batch scripts that do the following:
1) kill any running client
2) kill any running server
3) export the server from Godot
4) export the client from Godot
5) run the server
6) run the client with a command line Argument which the clients read and uses to automatically connect to the server

Step 6 is run 3 times by the script, and thanks to the command line arguments all 3 clients are now sitting in the lobby together, so all I have to do is click play and start testing.

My next step in developing this method is going to be making an editor plugin to run this scripts, so I just have a button in the editor to trigger them.

Here are my scripts currently:
https://github.com/FugitiveTheGame/Fugitive3D/tree/master/extras/scripts

And you could easily rewrite them as shell script for *nix if needed.

However, even with these scripts, it still takes some time. So I actually do about 60% of my testing using yet another method: depending on how your code is structured, I have a special scene, in my case called ```
FugitiveGame-dev.ts``` which mocks a lot of the things such as other clients, and starts it's own server. This allows me to run that scene directly from the editor, no other server, no other clients, skips the menus and lobby, so that I can iterate very quickly on gameplay things.

Also one last thing, I made some changes since I started using this client/server arcitecture. I will commit a change today to update this project.

**Comment by rccavalcante** [comment]
Thank you a lot man, really nice tips you just gave me. I'll start migrating my server code into my client project and use only one project from now on. Maintainability is what I'm looking for. I'm not concerned (yet) about memory and stuff, all I want is to make my life easier when I have some spare time to work with Godot.

Thanks for your quick response and your kindness.

**Comment by Wavesonics** [comment]
I'm going to close this one, feel free to open another with any more questions!
